### ISSUE TITLE
Redirect to openbesluitvorming.nl drops query parameters

### ISSUE THREAD

**Issue by jorritb** [ontola/raadstalk#23]
After searching for a term and then clicking on a municipality to go to the ORI search page (ex. `http://ori.argu.co/?zoekterm=%22klacht%22&organisaties=%5B%22ori_amsterdam_centrum*%22%5D`), the user is redirected from `ori.argu.co` to `openbesluitvorming.nl` but the query parameters are dropped so it goes to just `openbesluitvorming.nl` instead of `http://openbesluitvorming.nl/?zoekterm=%22klacht%22&organisaties=%5B%22ori_amsterdam_centrum*%22%5D`.

**Comment by joepio** [comment]
Changed the URL, fixed in production.
